name: CI One
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup client
        run: |
          curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
          testspace config url munderseth.stridespace.com
      - name: Push result to Testspace server
        run: |
           testspace [wf1]results.xml
        if: always()